plugins {
    id 'com.android.application'
}

android {
    namespace 'com.qret.mbd'
    compileSdk 34

    defaultConfig {
        applicationId "com.qret.mbd"
        minSdk 23
        targetSdk 34
        versionCode 3
        versionName "1.2"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}